version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - /home/ubuntu/Dataspace/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chambit-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
