name: Deploy Backend

on:
  push:
    paths:
      - 'chambit-be/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and restart container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/CodeSpace/service/chambit-be
            git pull origin main
            docker-compose down
            docker-compose up --build-d